export { default as ArrowLeft } from "./ArrowLeft";
export { default as ArrowRight } from "./ArrowRight";
export { default as PlayArrow } from "./PlayArrow";
export { default as Menu } from "./Menu";
export { default as Close } from "./Close";
export { default as ChevronRight } from "./ChevronRight";
export { default as Telescope } from "./Telescope";
export { default as Blackboards } from "./Blackboards";
export { default as Graduation } from "./Graduation";
